# name: current_directory
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - '**' # Include all branches
#       - '!main' # Exclude the main branch
# jobs :
#   current_dire :
#     runs-on :
#       labels: r1
#     steps :
#       - name: print pwd
#         run: pwd

name: Update and Run dbt Project on Runner

on:
  workflow_dispatch:
  push:
    branches:
      - '**' # Include all branches
      - '!main' # Exclude the main branch

jobs:
  update-code:
    name: Pull latest code and update dbt project
    runs-on: self-hosted  # 👈 your EC2 runner tag

    steps:
      - name: Identify branch
        run: echo "🔍 Triggered branch ${{ github.ref_name }}"
        
      - name: Go to project directory
        run: cd /home/ec2-user/dbt_setup
        
      # - name: Checkout triggering branch
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #     ref: ${{ github.ref_name }}
      
      - name: Print triggering branch
        run: echo "Triggered on branch ${{ github.ref_name }}"

      - name: Checkout triggering branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      # - name: Verify branch checkout
      #   run: |
      #     echo "Current Git branch:"
      #     git branch
      #     echo "Current directory:"
      #     pwd
      #     echo "Current commit:"
      #     git log -1 --oneline
          
      # - name: Pull latest code from the same branch that triggered the workflow
      #   working-directory: /home/ec2-user/dbt_setup
      #   run: |
      #     echo "Fetching latest code for branch: ${{ github.ref_name }}"
      #     git fetch origin ${{ github.ref_name }}
      #     git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
      #     git reset --hard origin/${{ github.ref_name }}
      #     git pull origin ${{ github.ref_name }}
      #     echo "✅ Code updated for branch: ${{ github.ref_name }}"


      - name: Fetch latest branches
        working-directory: /home/ec2-user/dbt_setup
        run: |
          # echo "Fetching all branches..."
          # git fetch origin
          # git branch -r
          # echo "Switching to branch: ${{ github.ref_name }}"
          # git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          # git reset --hard origin/${{ github.ref_name }}
          # git pull origin ${{ github.ref_name }}
          git branch

      - name: Activate virtual environment
        working-directory: /home/ec2-user/dbt_setup
        run: |
          git branch
          echo "Activating virtual environment..."
          source .venv/bin/activate

      - name: Go to snowflake project
        run: cd /home/ec2-user/dbt_setup/snowflake
        
      - name: print pwd
        run: pwd

      - name: Run dbt models
        working-directory: /home/ec2-user/dbt_setup/snowflake
        run: |
          source /home/ec2-user/dbt_setup/.venv/bin/activate
          echo "Activating virtual environment..."
          pwd
          dbt build
